### ISSUE TITLE
PlayerTab warnings

### ISSUE THREAD

**Issue by rudde0** [TlatoaniHJ/Tablisknu#1]
```
[Tablisknu] Task #1068849 for Tablisknu v1.0-BETA.6 generated an exception
java.lang.IllegalArgumentException: The player parameter in the constructor of PlayerTab must be online: CraftPlayer{name=oKeddy}
	at us.tlatoani.tablisknu.tablist.PlayerTab.<init>(PlayerTab.java:28) ~[?:?]
	at us.tlatoani.tablisknu.tablist.PlayerTablist.lambda$null$2(PlayerTablist.java:56) ~[?:?]
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_191]
	at us.tlatoani.tablisknu.tablist.PlayerTablist.lambda$getTab$3(PlayerTablist.java:56) ~[?:?]
	at java.util.Optional.flatMap(Unknown Source) ~[?:1.8.0_191]
	at us.tlatoani.tablisknu.tablist.PlayerTablist.getTab(PlayerTablist.java:56) ~[?:?]
	at us.tlatoani.tablisknu.tablist.PlayerTablist.lambda$null$18(PlayerTablist.java:203) ~[?:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_191]
	at us.tlatoani.tablisknu.core.util.OptionalUtil.consume(OptionalUtil.java:15) ~[?:?]
	at us.tlatoani.tablisknu.tablist.PlayerTablist.lambda$null$19(PlayerTablist.java:201) ~[?:?]
	at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_191]
	at us.tlatoani.tablisknu.tablist.PlayerTablist.lambda$applyChanges$20(PlayerTablist.java:200) ~[?:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:1.8.0_191]
	at us.tlatoani.tablisknu.core.util.OptionalUtil.consume(OptionalUtil.java:15) ~[?:?]
	at us.tlatoani.tablisknu.tablist.PlayerTablist.applyChanges(PlayerTablist.java:199) ~[?:?]
	at us.tlatoani.tablisknu.tablist.Tablist.applyChanges(Tablist.java:368) ~[?:?]
	at us.tlatoani.tablisknu.tablist.TablistGroup.lambda$add$0(TablistGroup.java:52) ~[?:?]
	at java.util.HashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_191]
	at us.tlatoani.tablisknu.tablist.TablistGroup.add(TablistGroup.java:50) ~[?:?]
	at us.tlatoani.tablisknu.tablist.TablistManager.lambda$onJoin$2(TablistManager.java:108) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-509]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-509]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-509]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

```

**Comment by TlatoaniHJ** [comment]
Is there a script that caused this and if so could you include it?

**Comment by rudde0** [comment]
I think, `set player's tablist name to "x"`

**Comment by TlatoaniHJ** [comment]
Can you include the full code (ex. if it was in a command, the full command, if it was in an event trigger, the full trigger, etc.) as well as the Bukkit/Spigot version and Skript version?

**Comment by rudde0** [comment]
This warning happening in my live server is online for few hours. I have no idea the exact code but I can send all of them. Server is running on Paper 1.13.2 build 510 and Skript 2.3.2
```
function liveRank(p: player):
	if {_p} has permission "r.Admin":
		set {_p}'s tablist name to "&c%{_p}%"
	else if {_p} has permission "r.SuperModerator":
		set {_p}'s tablist name to "&3Sr. Mod%{_p}%"
	else if {_p} has permission "r.Moderator":
		set {_p}'s tablist name to "&5Moderatör %{_p}%"

function teamColor(p: player, t: string = "join"):
	stop
	{_t} is "join":
		loop {team::%{isinateam::%{_p}%}%::list::*}:
			set {_checkedvalue} to "%loop-value%" parsed as player
			{_checkedvalue} is set
			{_checkedvalue} isn't {_p}
			set {_p}'s nametag for {_checkedvalue} to "&a%{_p}%"
			set {_checkedvalue}'s nametag for {_p} to "&a%{_checkedvalue}%"
	else if {_t} is "quit":
		loop {team::%{isinateam::%{_p}%}%::list::*}:
			set {_checkedvalue} to "%loop-value%" parsed as player
			{_checkedvalue} is set
			{_checkedvalue} isn't {_p}
			{_p} has permission "r.VIP":
				set {_c} to "&b"
			else:
				set {_c} to ""
			loop-value has permission "r.VIP":
				set {_v} to "&b"
			else:
				set {_v} to ""
			set {_p}'s nametag for {_checkedvalue} to "%{_c}%%{_p}%"
			set loop-value's nametag for {_p} to "%{_v}%%loop-value%"
```

**Comment by TlatoaniHJ** [comment]
What is the context in which these functions are being called? Also, what is your ProtocolLib version?

**Comment by rudde0** [comment]
They work on join event. My ProtocolLib version is 4.4.0

**Comment by TlatoaniHJ** [comment]
When a player joins, you should use a delay of at least 2 seconds before doing tablist modifications with them. Try this and see if anything changes.

**Comment by rudde0** [comment]
When someone disconnect with reason "java.io.ioexception: an existing connection was forcibly closed by the remote host", happening this warning in console and tab manager is crashing.

**Comment by rudde0** [comment]
still have issue. :(

**Comment by rudde0** [comment]
I found the exactly happen of the error:
- I joined to the server with 2 accounts named rudde and Unknown
- I left from server with Unknown
- I left from server with rudde
- I join to the server with rudde and error started here, player tablist names have broken

Issue continued until Unknown join.

**Comment by TlatoaniHJ** [comment]
In your server, run the command `/tablisknu update snapshot`, and restart your server. Once your server has been restarted, you should be running Tablisknu 1.0-BETA.7-SNAPSHOT.0. Make sure that this is the version you are running using `/tablisknu ver`. Once that is checked, see if this issue still occurs.

**Comment by rudde0** [comment]
Fixed, thanks!
