### ISSUE TITLE
"Please create an issue regarding this on Tablisknu's GitHub page"

### ISSUE THREAD

**Issue by AKtomik** [TlatoaniHJ/Tablisknu#9]
```
[Server thread/INFO]: [Tablisknu] Enabling Tablisknu v1.0
[Server thread/WARN]: java.lang.IllegalArgumentException: Cannot find net.minecraft.server.v1_19_R2.DedicatedPlayerList
[Server thread/WARN]: at Tablisknu-1.0.jar//us.tlatoani.tablisknu.core.reflection.Reflection.getCanonicalClass(Reflection.java:413)
[Server thread/WARN]: at Tablisknu-1.0.jar//us.tlatoani.tablisknu.core.reflection.Reflection.getMinecraftClass(Reflection.java:390)
[Server thread/WARN]: at Tablisknu-1.0.jar//us.tlatoani.tablisknu.core.reflection.Reflection.<clinit>(Reflection.java:38)
[Server thread/WARN]: at Tablisknu-1.0.jar//us.tlatoani.tablisknu.skin.ProfileManager.loadReflectionStuff(ProfileManager.java:64)
[Server thread/WARN]: at Tablisknu-1.0.jar//us.tlatoani.tablisknu.skin.ProfileManager.load(ProfileManager.java:46)
[Server thread/WARN]: at Tablisknu-1.0.jar//us.tlatoani.tablisknu.Tablisknu.onEnable(Tablisknu.java:65)
[Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
[Server thread/WARN]: at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
[Server thread/WARN]: at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
[Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:301)
[Server thread/WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R2.DedicatedPlayerList
[Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177)
[Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
[Server thread/WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[Server thread/WARN]: at java.base/java.lang.Class.forName0(Native Method)
[Server thread/WARN]: at java.base/java.lang.Class.forName(Class.java:375)
[Server thread/WARN]: at Tablisknu-1.0.jar//us.tlatoani.tablisknu.core.reflection.Reflection.getCanonicalClass(Reflection.java:411)
[Server thread/WARN]: ... 16 more
[Server thread/INFO]: [Tablisknu] An exception has occured within Tablisknu
[Server thread/INFO]: [Tablisknu] Please create an issue regarding this on Tablisknu's GitHub page: (no github link available yet, but you can join the skript discord chat at https://discord.gg/vb9dGbu for help)
[Server thread/INFO]: [Tablisknu] You can also run the '/tablisknu desc' command and go to one of the links provided for help.
[Server thread/INFO]: [Tablisknu] Bukkit/Spigot version: git-Paper-366 (MC: 1.19.3)
[Server thread/INFO]: [Tablisknu] Skript version: 2.6.4
[Server thread/INFO]: [Tablisknu] Tablisknu version: 1.0
[Server thread/INFO]: [Tablisknu] Exception at ProfileManager
[Server thread/WARN]: java.lang.IllegalArgumentException: Cannot find net.minecraft.server.v1_19_R2.EntityPlayer
[Server thread/WARN]: at Tablisknu-1.0.jar//us.tlatoani.tablisknu.core.reflection.Reflection.getCanonicalClass(Reflection.java:413)
[Server thread/WARN]: at Tablisknu-1.0.jar//us.tlatoani.tablisknu.core.reflection.Reflection.getMinecraftClass(Reflection.java:390)
[Server thread/WARN]: at Tablisknu-1.0.jar//us.tlatoani.tablisknu.skin.ProfileManager.loadReflectionStuff(ProfileManager.java:64)
[Server thread/WARN]: at Tablisknu-1.0.jar//us.tlatoani.tablisknu.skin.ProfileManager.load(ProfileManager.java:46)
[Server thread/WARN]: at Tablisknu-1.0.jar//us.tlatoani.tablisknu.Tablisknu.onEnable(Tablisknu.java:65)
[Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
[Server thread/WARN]: at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
[Server thread/WARN]: at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
[Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
[Server thread/WARN]: at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
[Server thread/WARN]: at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:301)
[Server thread/WARN]: at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[Server thread/WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[Server thread/WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R2.EntityPlayer
[Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177)
[Server thread/WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124)
[Server thread/WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[Server thread/WARN]: at java.base/java.lang.Class.forName0(Native Method)
[Server thread/WARN]: at java.base/java.lang.Class.forName(Class.java:375)
[Server thread/WARN]: at Tablisknu-1.0.jar//us.tlatoani.tablisknu.core.reflection.Reflection.getCanonicalClass(Reflection.java:411)
[Server thread/WARN]: ... 15 more
[Server thread/WARN]: [ProtocolLib] [PacketFilterManager] Plugin Tablisknu tried to register listener for unknown packet PLAYER_INFO[PLAY, SERVER, 55, classNames: [net.minecraft.network.protocol.game.PacketPlayOutPlayerInfo, net.minecraft.network.protocol.game.ClientboundPlayerInfoPacket, net.minecraft.network.play.server.SPacketPlayerListItem] (unregistered)] [direction: from SERVER]
[Server thread/WARN]: [ProtocolLib] [PacketFilterManager] Plugin Tablisknu tried to register listener for unknown packet PLAYER_INFO[PLAY, SERVER, 55, classNames: [net.minecraft.network.protocol.game.PacketPlayOutPlayerInfo, net.minecraft.network.protocol.game.ClientboundPlayerInfoPacket, net.minecraft.network.play.server.SPacketPlayerListItem] (unregistered)] [direction: from SERVER] 
```

**Comment by Symmettry** [comment]
tablisknu is outdated.
